config/routes.rb
Rails.application.routes.draw do
  get '/ba/download' => 'binomio_admin/editables#download', as: :ba_download
  get '/ba/editables' => 'binomio_admin/editables#index', as: :ba_editables_index
  patch '/ba/editable' => 'binomio_admin/editables#update'
  get '/ba/editor' => 'binomio_admin/editables#help', as: :ba_help
end

app/models/binomio_admin/editable.rb
module BinomioAdmin
  class Editable < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: { maximum: 128 }
    validates :value, length: { maximum: 16384 }
    has_one_attached :image # Optionally, for image fields
    has_one_attached :download # Optionally, for download fields

    # Given a name, get the associated Editable if it doesn't exist, a new one if it doesn't
    def self.find_or_create name
      self.find_by_name(name) || Editable.new(name: name, value: nil)
    end

    # Given a name, get the value associated to its Editable if it exists, or nil if it doesn't
    def self.value_of name
      editable = self.find_by_name(name)
      editable ? editable.value : nil
    end

    # Returns true if there's either an image or download attached to this editable
    def attached?
      image.attached? || download.attached?
    end
  end
end

app/controllers/binomio_admin/editables_controller.rb
require 'open-uri'
module BinomioAdmin
  class EditablesController < ApplicationController
    before_action :authorize_user, except: [:download]
    SEPARATOR = "%"
    HOST = Rails.configuration.host

    # Shows all Editables in a hierarchical view
    def index
      @tree = {}
      Editable.find_each do |editable|
        @tree.nested_set(editable.name.split("."), editable)
      end
    end

    # Given the key of an editable download, redirect to the download page for it
    def download
      editable = Editable.find_by_name params[:name]
      render plain: "La descarga solicitada no existe" and return if editable.blank?
      render plain: "La descarga solicitada no está disponible" and return unless editable.download.attached?
      redirect_to rails_blob_path(editable.download, disposition: "inline")
    end

    # Method called by the editor to mass-update all fields
    def update
      text_fields = params.to_unsafe_h[:textFields] # Name format: name
      image_fields = params.to_unsafe_h[:imageFields] # Name format: EntityClass%id%attribute_name
      image_collection_fields = params.to_unsafe_h[:collectionImageFields] # Name format: EntityClass%id%attribute_name%attachment_id
      download_fields = params.to_unsafe_h[:downloadFields]
      render json: { message: "No hay campos para actualizar" }, status: 400 and return if text_fields.blank? && image_fields.blank? && image_collection_fields.blank? && download_fields.blank?
      begin
        Editable.transaction do
          update_text_fields(text_fields) if text_fields.present?
          update_image_fields(image_fields) if image_fields.present?
          update_image_collection_fields(image_collection_fields) if image_collection_fields.present?
          update_download_fields(download_fields) if download_fields.present?
        end
      rescue Exception => ex
        puts "#{ex.class}: #{ex.message}"
        puts ex.backtrace.join("\n")
        render json: { message: "Ocurrió un error: #{ex.message}. No se han aplicado cambios." }, status: 400 and return
      end
      render json: { message: "Actualizado exitosamente" }, status: 200
    end

    private

    # Mass-update all text fields
    def update_text_fields fields
      fields.each do |key, value|
        if key_is_for_an_entity? key
          entity, attribute_name = key_to_entity key
          entity.public_send("#{attribute_name}=", value)
          entity.save!
        else
          editable = Editable.find_or_create key
          editable.value = value
          editable.save!
        end
      end
    end

    # Mass-update all image fields (not including collections)
    def update_image_fields fields
      fields.each do |key, value|
        next if value.starts_with?("/rails") || value.include?(HOST) # User didn't change this image, so we skip it
        io = BinomioAdmin::Images.transform_and_convert_to_io value, key
        if key_is_for_an_entity? key
          entity, attribute_name = key_to_entity key
          attachment = entity.public_send("#{attribute_name}")
        else
          entity = Editable.find_or_create key
          attachment = entity.image
        end
        attachment.attach(io: io, filename: "image")
        entity.save!
      end
    end

    # Mass-update all image collections
    # Receives a list of fields like: {
    #   "CoreModel%50%slider_images%15" => "/someurl", # Existing attachment with ID 15, we ignore
    #   "CoreModel%50%slider_images%0" => "data:image/jpeg..." # New attachment (ID 0), we add
    # }
    def update_image_collection_fields fields
      # TODO: rewrite to accept external urls
      collections = {}
      fields.each do |key, value|
        parts = key.rpartition SEPARATOR # "a%b%c%d" => ["a%b%c", "%", "d"]
        collections[parts[0]] = [] if collections[parts[0]].nil?
        collections[parts[0]] << { id: parts[2].to_i, dataurl: value }
      end
      collections.each do |key, new_attachments|
        entity, attribute_name = key_to_entity key
        old_attachments = entity.public_send(attribute_name)
        # Old attachments not sent in the request are assumed to be deleted by the user, so we purge them
        old_attachments.each do |old_attachment|
          unless new_attachments.any? { |a| a[:id] == old_attachment.id }
            old_attachment.purge
          end
        end
        # New attachments not present should be added to the collection
        new_attachments.each do |new_attachment|
          if new_attachment[:dataurl].starts_with? "data:"
            unless old_attachments.any? { |a| a.id == new_attachment[:id] }
              old_attachments.attach(io: src_to_io(new_attachment[:dataurl]), filename: "image")
            end
          end
        end
      end
    end

    # Mass-update all downloads, working in the same way as update_image_fields
    def update_download_fields fields
      fields.each do |key, value|
        if key_is_for_an_entity? key
          entity, attribute_name = key_to_entity key
          attachment = entity.public_send("#{attribute_name}")
          filename = "download"
        else
          entity = Editable.find_or_create key
          attachment = entity.download
          filename = entity.value || "download"
        end
        attachment.attach(io: src_to_io(value), filename: filename)
        entity.save!
      end
    end

    # Returns true if the key refers to an entity's attribute, or false if it's just an Editable
    def key_is_for_an_entity? key
      key.include? SEPARATOR
    end

    # When you use the 'editable' helper with an entity, the editable field contains a key that identifies the entity
    # It looks like 'Book%123%author', where the format is 'Class%ID%attribute'
    # This method returns the entity that a key refers to, and also the attribute name
    def key_to_entity key
      parts = key.split SEPARATOR
      raise "Invalid key: #{key}" if parts.length != 3
      entity_class = Object.const_get parts[0]
      entity_id = parts[1].to_i
      attribute_name = parts[2]
      return entity_class.find(entity_id), attribute_name
    end

    # Converts an <img> src into an IO object so that we can attach it
    def src_to_io url
      if url.starts_with? "data" # If the src is a dataurl with a base64-encoded image
        StringIO.new(Base64.decode64(url.split(",")[1]))
      else # If the src is an external image URL
        begin
          result = open(url) # May return either a Tempfile or StringIO
          return result.class == Tempfile ? File.open(result.path) : result
        rescue Exception => ex
          puts "#{ex.class}: #{ex.message}"
          raise "No se pudo obtener la imagen: #{url}"
        end
      end

    end

    # This method is called before all edition actions. The implementing project is
    # encouraged to override it with custom authorizations if desired.
    def authorize_user
      authenticate_user!
    end
  end
end
class Hash
  # Set the value of a nested hash even if the parents don't exist. For example, given a list
  # of keys like [:a, :b, :c] and a value (like 27), make it so that self[:a][:b][:c] = 27
  def nested_set keys, value
    if keys.length == 1
      self[keys[0]] = value
    else
      self[keys[0]] = {} unless self.include? keys[0]
      self[keys[0]].nested_set keys[1..-1], value
    end
  end
end

app/helpers/binomio_admin/editables_helper.rb
module BinomioAdmin
  module EditablesHelper
    DEFAULT_MISSING_IMAGE = "binomio_admin/missing_image_square.svg"
    MISSING_TEXT = "Insertar texto aquí"
    
    # Generates an editable field for a given entity's text attribute
    def editable_text entity, attribute, options = {}, html_options = {}
      attributes = {
        class: "editable-text #{html_options[:class]}",
        "data-key": entity_attr_to_key(entity, attribute),
        "data-changed": false,
        "data-notes": options[:notes]
      }
      content_tag :span, (entity.public_send(attribute) || MISSING_TEXT).to_s.html_safe, html_options.merge(attributes)
    end

    # Generates en editable field stored as an Editable entity in database
    def editable_text_named name, options = {}, html_options = {}
      attributes = {
        class: "editable-text #{html_options[:class]}",
        "data-key": name,
        "data-changed": false,
        "data-notes": options[:notes],
        "data-size": options[:size]
      }
      content_tag :span, (Editable.value_of(name) || MISSING_TEXT).to_s.html_safe, html_options.merge(attributes)
    end

    # Generates an editable field for a given entity's image attribute with ActiveStorage
    def editable_image entity, attribute, options = {}, html_options = {}
      attachment = entity.public_send(attribute)
      html_options[:class] = "editable-image #{html_options[:class]}"
      html_options[:"data-key"] = entity_attr_to_key(entity, attribute)
      html_options[:"data-changed"] = false
      image_tag get_url(attachment, options[:missing_image]), html_options
    end

    # Generates an editable image field stored as an Editable entity with ActiveStorage attachent
    def editable_image_named name, options = {}, html_options = {}
      attachment = Editable.find_or_create(name).image
      html_options[:class] = "editable-image #{html_options[:class]}"
      html_options[:"data-key"] = name
      html_options[:"data-changed"] = false
      image_tag get_url(attachment, options[:missing_image]), html_options
    end

    # Generates an editable image field for one of a given entity's image attachments
    # If the attachent is nil, it'll be interpreted as a blank field to upload a new image to the collection
    def editable_collection_image entity, attribute, attachment, options = {}, html_options = {}
      html_options[:class] = "editable-collection-image #{html_options[:class]}"
      html_options[:"data-key"] = entity_item_to_key(entity, attribute, attachment)
      url = get_url attachment, options[:missing_image]
      image_tag url, html_options
    end

    # Generates an editable download field for a given entity's attachment attribute
    # You can pass a custom HREF, or let ActiveStorage generate one for you by default
    def editable_download entity, attribute, options = {}, html_options = {}
      attributes = {
        href: html_options[:href] || get_url(entity.public_send(attribute), options[:missing_file]),
        target: "_blank",
        class: "editable-download #{html_options[:class]}",
        "data-key": entity_attr_to_key(entity, attribute),
        "data-changed": false
      }
      content_tag :a, html_options.merge(attributes) do yield end
    end

    # Generates an editable download field stored as an Editable entity with an ActiveStorage attachment
    # You can pass a custom HREF, or let ActiveStorage generate one for you by default
    def editable_download_named name, options = {}, html_options = {}
      attributes = {
        href: html_options[:href] || ba_download_path(name: name),
        target: "_blank",
        class: "editable-download #{html_options[:class]}",
        "data-key": name,
        "data-changed": false
      }
      content_tag :a, html_options.merge(attributes) do yield end
    end

    # Given the name of an editable, return its associated image's URL
    def name_to_url name, missing_file = nil
      get_url Editable.find_or_create(name).image, missing_file
    end

    # Generate the HTML of editable name tree that's shown on the editable index page
    def display_tree node, level = 0
      return node.sort.map{|key, child_node|
        if child_node.is_a? Hash
          "<div style='padding-left:#{level * 20}px'>⚫ <b>#{key}</b>:</div>" + display_tree(child_node, level + 1)
        else
          if child_node.image.attached?
            value = editable_image_named child_node.name, {}, style: "max-height: 18px;"
          elsif child_node.download.attached?
            value = editable_download_named child_node.name do content_tag :span, "📄" end
          elsif child_node.value == ""
            value = editable_download_named child_node.name do content_tag :span, "❎" end
          else
            value = editable_text_named child_node.name
          end
          "<div style='padding-left:#{level * 20}px'>⚫ <b>#{key}</b>: #{value}</div>"
        end
      }.join
    end

    private

    # Given an ActiveStorage Attachment/Attached::Many/Attached::One, return its accessible URL
    def get_url attachment, missing_image = DEFAULT_MISSING_IMAGE
      missing_image ||= DEFAULT_MISSING_IMAGE # In case nil is passed
      if attachment.nil?
        image_path(missing_image)
      elsif attachment.class == ActiveStorage::Attachment
        url_for(attachment)
      else
        attachment.attached? ? url_for(attachment) : image_path(missing_image)
      end
    end

    # Generate a string key to represent an entity's attribute
    def entity_attr_to_key entity, attribute
      "#{entity.class.name}%#{entity.id}%#{attribute}"
    end

    # Generate a string key to represent an attachment within an entity's collection attribute
    def entity_item_to_key entity, attribute, attachment
      "#{entity.class.name}%#{entity.id}%#{attribute}%#{attachment.present? ? attachment.id : 0}"
    end
  end
end

app/views/binomio_admin/_editor.html.erb
<%= stylesheet_link_tag 'binomio_admin/all' %>
<%= javascript_include_tag 'binomio_admin/all' %>

<!-- Editor footer -->
<div id="divEditorFooter">
  <div id="divEditorLeft">
    <a href="<%= ba_help_path %>" target="_blank"><i class="fa fa-question-circle" title="Abrir la página de ayuda (en una nueva pestaña)"></i></a>
    <a href="#" id="btnGlow"><i class="fa fa-pencil" title="Resaltar las partes editables de la página"></i></a>
    <a href="#" id="btnResetEmptyText"><i class="fa fa-eye" title="Volver a mostrar los campos de texto que fueron ocultados"></i></a>
    <% if defined? admin_menu_path %>
      <a href="<%= admin_menu_path %>"><i class="fa fa-wrench" title="Ir al menú administrativo"></i></a>
    <% end %>
  </div>
  <div id="divEditorCenter" class="center">
  </div>
  <div id="divEditorRight">
    <button id="btnDiscardEdits" class="btn btn-danger editor-button">
      <i class="fa fa-times"></i><span> Descartar cambios</span>
    </button>
    <button id="btnSaveEdits" class="btn btn-success editor-button">
      <i class="fa fa-check"></i><span> Publicar cambios</span>
    </button>
  </div>
</div>

<!-- Popup for text edition -->
<div id="divTextPopper" class="edition-popper" style="display:none">
  <textarea id="tarNewText" class="form-control"></textarea><br/>
  <button id="btnDiscardText" class="btn btn-danger"><i class="fa fa-times"></i></button>
  <button id="btnSaveText" class="btn btn-success"><i class="fa fa-check"></i></button><br>
  <span id="spnTextNotes"></span>
</div>

<!-- Popup for image edition -->
<div id="divImagePopper" class="edition-popper ba-center" style="display: none;">
  <span id="spnPopperSize"></span><br />
  <span id="btnUploadImage"><i class="fa fa-upload"></i> Subir imagen</span><br />
  <span id="btnUploadUrl"><i class="fa fa-external-link"></i> Cargar desde URL</span>
  <input type="file" id="filUploadImage"/>
</div>

<!-- Popup for download edition -->
<div id="divDownloadPopper" class="edition-popper ba-center" style="display: none;">
  <a id="btnDownloadDownload" href="#" target="_blank" style="color:white"><i class="fa fa-download"></i> Descargar archivo</a><br/>
  <span id="btnUploadDownload"><i class="fa fa-upload"></i> Reemplazar archivo</span>
  <input type="file" id="filUploadDownload"/>
</div>

<!-- Modal for importing images from URL -->
<div class="modal fade" id="divMessageModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><i class="fa fa-info-circle"></i></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="divMessage" class="modal-body">
      </div>
    </div>
  </div>
</div>

<!-- Modal for importing images from URL -->
<div class="modal fade" id="divUrlModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cargar desde URL</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Ingresa la URL de la imagen que deseas subir.<br />
        <input type="text" class="form-input" id="txtImageUrl" style="width:100%"/>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button id="btnLoadUrl" type="button" class="btn btn-primary">Aceptar</button>
      </div>
    </div>
  </div>
</div>